# -*- coding: utf-8 -*-
"""LibraryManagementSystem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RzjvsNFQ2Yp-bguTDN1xoL51MtlJAV3s
"""

class Library:
    def __init__(self):
        self.file_name = "books.txt"
        self.file = open(self.file_name, "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books = self.file.readlines()
        for book in books:
            bookInfo = book.strip().split(',')
            print(f"Title: {bookInfo[0]}, Author: {bookInfo[1]}")

    def add_book(self):
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        releaseYear = input("Enter release year: ")
        numPages = input("Enter number of pages: ")
        bookInfo = f"{title},{author},{releaseYear},{numPages}\n"
        self.file.write(bookInfo)
        print("Book added.")

    def remove_book(self):
        title = input("Enter the title of the book to remove: ")
        self.file.seek(0)
        books = self.file.readlines()
        updatedBooks = []
        removed = False
        for book in books:
            if title not in book:
                updatedBooks.append(book)
            else:
                removed = True
        if removed:
            self.file.seek(0)
            self.file.truncate()
            self.file.writelines(updatedBooks)
            print(f"Book '{title}' removed.")
        else:
            print(f"Book '{title}' not found.")

lib = Library()

while True:
    print("\nLibrary Management System")
    print("1. List Books")
    print("2. Add Book")
    print("3. Remove Book")
    print("4. Exit")
    choice = input("Enter your choice: ")

    if choice == '1':
        lib.list_books()
    elif choice == '2':
        lib.add_book()
    elif choice == '3':
        lib.remove_book()
    elif choice == '4':
        del lib
        print("Exiting...")
        break
    else:
        print("Invalid choice. Please try again.")

